import 'dart:convert';
import 'dart:io';
import 'package:serverpod/serverpod.dart';
import 'package:jose/jose.dart';

import '../generated/protocol.dart';

/// PowerSync JWT endpoint for client authentication
///
/// Issues JWT tokens for PowerSync client authentication.
/// Tokens include user_id claim for sync bucket filtering.
/// Uses RS256 signing with RSA keys for PowerSync verification.
class PowerSyncEndpoint extends Endpoint {
  @override
  bool get requireLogin => true;

  /// Get PowerSync JWT token for authenticated user
  ///
  /// Returns a [PowerSyncToken] containing the JWT token, expiry time,
  /// and PowerSync endpoint URL.
  ///
  /// Token expires in 5 minutes - client should refresh before expiry.
  Future<PowerSyncToken> getToken(Session session) async {
    session.log('PowerSync: getToken called', level: LogLevel.info);

    // Debug: Check authentication state
    if (session.authenticated == null) {
      session.log(
        'PowerSync: ERROR - session.authenticated is null',
        level: LogLevel.error,
      );
      throw Exception('User not authenticated');
    }

    final accountUuid = session.authenticated!.userIdentifier;
    if (accountUuid.isEmpty) {
      session.log(
        'PowerSync: ERROR - userIdentifier is empty',
        level: LogLevel.error,
      );
      throw Exception('User identifier is empty');
    }

    session.log(
      'PowerSync: Generating token for account...',
      level: LogLevel.info,
    );

    // Use account UUID as JWT identity for sync bucket filtering
    final token = await _createPowerSyncToken(accountUuid, session);

    // Token expires in 5 minutes
    final expiresAt = DateTime.now().add(const Duration(minutes: 5));

    // Get PowerSync endpoint from environment or construct from server FQDN
    final powerSyncEndpoint =
        Platform.environment['POWERSYNC_URL'] ?? _constructPowerSyncUrl();

    session.log(
      'PowerSync: Token generated successfully, endpoint: $powerSyncEndpoint',
      level: LogLevel.info,
    );

    return PowerSyncToken(
      token: token,
      expiresAt: expiresAt.toIso8601String(),
      endpoint: powerSyncEndpoint,
    );
  }
}

/// Construct PowerSync URL from server FQDN
String _constructPowerSyncUrl() {
  final serverFqdn = Platform.environment['OPENOPS_SERVER_FQDN'];
  if (serverFqdn != null && serverFqdn.isNotEmpty) {
    return 'https://$serverFqdn/powersync/';
  }
  // Fallback to localhost for development
  return 'http://localhost:8105';
}

/// Create RS256 signed JWT for PowerSync authentication using jose library
///
/// Uses JWK format private key from environment variables generated by setup_jwk.sh
/// Falls back to PEM format for development (generated by generate_powersync_keys.sh)
Future<String> _createPowerSyncToken(String accountUuid, Session session) async {
  // Try JWK format first (production - setup_jwk.sh)
  final signingKeyBase64 =
      Platform.environment['POWERSYNC_JWT_PRIVATE_KEY_JWK'];

  if (signingKeyBase64 != null && signingKeyBase64.isNotEmpty) {
    return _createTokenWithJWK(accountUuid, session, signingKeyBase64);
  }

  // Fall back to PEM format (development - generate_powersync_keys.sh)
  final signingKeyPemBase64 =
      Platform.environment['POWERSYNC_JWT_PRIVATE_KEY_PEM'];

  if (signingKeyPemBase64 != null && signingKeyPemBase64.isNotEmpty) {
    return _createTokenWithPEM(accountUuid, session, signingKeyPemBase64);
  }

  throw Exception(
    'No PowerSync JWT signing key found. Set either POWERSYNC_JWT_PRIVATE_KEY_JWK or POWERSYNC_JWT_PRIVATE_KEY_PEM',
  );
}

/// Create JWT using JWK format (production)
Future<String> _createTokenWithJWK(
  String accountUuid,
  Session session,
  String signingKeyBase64,
) async {
  try {
    session.log(
      'PowerSync JWT: Using JWK format key for account: "$accountUuid"',
      level: LogLevel.info,
    );

    // Decode base64 JWK
    final jwkBytes = base64.decode(signingKeyBase64);
    final jwkString = utf8.decode(jwkBytes);

    // Parse JWK with jose library
    final jwkMap = jsonDecode(jwkString) as Map<String, dynamic>;
    final key = JsonWebKey.fromJson(jwkMap);
    session.log(
      'PowerSync JWT: JWK parsed successfully, kty: ${jwkMap['kty']}, kid: ${jwkMap['kid']}',
      level: LogLevel.info,
    );

    return _signJWT(accountUuid, session, key);
  } catch (e, stackTrace) {
    session.log(
      'PowerSync JWT: ERROR with JWK format: $e',
      level: LogLevel.error,
    );
    session.log(
      'PowerSync JWT: Stack trace: $stackTrace',
      level: LogLevel.error,
    );
    throw Exception('JWT generation with JWK failed: ${e.toString()}');
  }
}

/// Create JWT using PEM format (development)
Future<String> _createTokenWithPEM(
  String accountUuid,
  Session session,
  String signingKeyPemBase64,
) async {
  try {
    session.log(
      'PowerSync JWT: Using PEM format key for account: "$accountUuid"',
      level: LogLevel.info,
    );

    // Decode base64 PEM
    final pemBytes = base64.decode(signingKeyPemBase64);
    final pemString = utf8.decode(pemBytes);

    // Create JWK from PEM using jose library
    final key = JsonWebKey.fromPem(pemString);
    session.log(
      'PowerSync JWT: PEM converted to JWK successfully',
      level: LogLevel.info,
    );

    return _signJWT(accountUuid, session, key);
  } catch (e, stackTrace) {
    session.log(
      'PowerSync JWT: ERROR with PEM format: $e',
      level: LogLevel.error,
    );
    session.log(
      'PowerSync JWT: Stack trace: $stackTrace',
      level: LogLevel.error,
    );
    throw Exception('JWT generation with PEM failed: ${e.toString()}');
  }
}

/// Sign JWT using jose library (common for both JWK and PEM)
Future<String> _signJWT(String accountUuid, Session session, JsonWebKey key) async {
  // Create JWT payload
  final now = DateTime.now();
  final expiry = now.add(const Duration(minutes: 5));

  final claims = JsonWebTokenClaims.fromJson({
    'sub': accountUuid,
    'user_id': accountUuid, // PowerSync uses this for sync bucket filtering
    'iat': now.millisecondsSinceEpoch ~/ 1000,
    'exp': expiry.millisecondsSinceEpoch ~/ 1000,
    'aud': 'powersync',
    'iss': 'quanitya-cloud',
  });
  session.log(
    'PowerSync JWT: Claims created: ${claims.toJson().keys.join(', ')}',
    level: LogLevel.info,
  );

  // Create and sign JWT using jose library
  final builder = JsonWebSignatureBuilder()
    ..jsonContent = claims.toJson()
    ..addRecipient(key, algorithm: 'RS256');

  final jws = builder.build();
  final token = jws.toCompactSerialization();
  session.log(
    'PowerSync JWT: Token signed successfully, length: ${token.length}',
    level: LogLevel.info,
  );

  return token;
}
