import 'package:health/health.dart';
import 'package:injectable/injectable.dart';
import 'package:uuid/uuid.dart';

import '../../../../logic/log_entries/models/log_entry.dart';
import '../../../../logic/templates/models/shared/tracker_template.dart';
import '../../../../logic/templates/models/shared/template_field.dart';
import '../../../../logic/templates/enums/field_enum.dart';
import '../../../logic/ingestion/adapters/flutter_data_source_adapter.dart';

/// Factory that auto-generates adapters from HealthDataType enum.
///
/// Instead of manually creating an adapter for each health type,
/// this factory derives adapters dynamically based on the enum value.
///
/// Example:
/// ```dart
/// final factory = getIt&lt;HealthAdapterFactory&gt;();
/// final stepsAdapter = factory.create(HealthDataType.STEPS);
/// 
/// // Use with DataIngestionService
/// await ingestionService.syncFlutter(
///   adapter: stepsAdapter,
///   templateId: templateId,
///   sourceData: healthDataPoints,
/// );
/// ```
@lazySingleton
class HealthAdapterFactory {
  /// Creates a FlutterDataSourceAdapter for the given HealthDataType.
  ///
  /// The generated adapter:
  /// - Has adapterId = "health.{typename}" (e.g., "health.steps")
  /// - Has human-readable displayName (e.g., "Steps")
  /// - Derives TrackerTemplateModel with appropriate field type
  /// - Maps HealthDataPoint to LogEntryModel with metadata
  FlutterDataSourceAdapter<HealthDataPoint> create(HealthDataType type) {
    return _DerivedHealthAdapter(type);
  }

  /// Creates adapters for multiple health types.
  List<FlutterDataSourceAdapter<HealthDataPoint>> createAll(
    List<HealthDataType> types,
  ) {
    return types.map(create).toList();
  }
}

/// Internal adapter implementation generated by HealthAdapterFactory.
class _DerivedHealthAdapter extends FlutterDataSourceAdapter<HealthDataPoint> {
  final HealthDataType type;

  _DerivedHealthAdapter(this.type);

  @override
  String get adapterId => 'health.${type.name.toLowerCase()}';

  @override
  String get displayName => _humanize(type.name);

  @override
  TrackerTemplateModel deriveTemplate() {
    return TrackerTemplateModel.create(
      name: displayName,
      fields: [
        TemplateField.create(
          label: 'Value',
          type: _deriveFieldType(type),
        ),
      ],
    );
  }

  @override
  LogEntryModel mapToEntry(HealthDataPoint sourceData, String templateId) {
    return LogEntryModel(
      id: const Uuid().v4(),
      templateId: templateId,
      scheduledFor: null, // Health imports are always "logged"
      occurredAt: sourceData.dateTo,
      data: {
        'value': _extractValue(sourceData.value),
        '_sourceAdapter': adapterId,
        '_dedupKey': extractDedupKey(sourceData),
        '_healthUuid': sourceData.uuid,
        '_healthSource': sourceData.sourceId,
        '_healthSourceName': sourceData.sourceName,
        '_healthUnit': sourceData.unit.name,
      },
      updatedAt: DateTime.now(),
    );
  }

  @override
  String extractDedupKey(HealthDataPoint sourceData) {
    // Use the health platform's UUID as the dedup key
    return sourceData.uuid;
  }

  @override
  DateTime extractTimestamp(HealthDataPoint sourceData) {
    return sourceData.dateTo;
  }

  /// Converts enum name to human-readable display name.
  /// HEART_RATE → "Heart Rate"
  /// BLOOD_OXYGEN → "Blood Oxygen"
  static String _humanize(String enumName) {
    return enumName
        .split('_')
        .map((word) => word.isEmpty 
            ? '' 
            : word[0].toUpperCase() + word.substring(1).toLowerCase())
        .join(' ');
  }

  /// Derives the appropriate FieldEnum type for a health data type.
  static FieldEnum _deriveFieldType(HealthDataType type) {
    // Most health data is numeric (float)
    // Integer types are counts or durations in minutes
    return switch (type) {
      HealthDataType.STEPS => FieldEnum.integer,
      HealthDataType.FLIGHTS_CLIMBED => FieldEnum.integer,
      HealthDataType.EXERCISE_TIME => FieldEnum.integer,
      HealthDataType.SLEEP_ASLEEP => FieldEnum.integer,
      HealthDataType.SLEEP_AWAKE => FieldEnum.integer,
      HealthDataType.SLEEP_AWAKE_IN_BED => FieldEnum.integer,
      HealthDataType.SLEEP_IN_BED => FieldEnum.integer,
      HealthDataType.SLEEP_DEEP => FieldEnum.integer,
      HealthDataType.SLEEP_LIGHT => FieldEnum.integer,
      HealthDataType.SLEEP_REM => FieldEnum.integer,
      HealthDataType.SLEEP_OUT_OF_BED => FieldEnum.integer,
      HealthDataType.SLEEP_SESSION => FieldEnum.integer,
      HealthDataType.SLEEP_UNKNOWN => FieldEnum.integer,
      HealthDataType.APPLE_STAND_HOUR => FieldEnum.integer,
      _ => FieldEnum.float, // Default to float for most measurements
    };
  }

  /// Extracts the numeric value from a HealthValue.
  static dynamic _extractValue(HealthValue value) {
    if (value is NumericHealthValue) {
      return value.numericValue;
    }
    // Handle other value types as needed
    // AudiogramHealthValue, WorkoutHealthValue, etc.
    return null;
  }
}
