import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:flutter/foundation.dart';
import 'package:cubit_ui_flow/cubit_ui_flow.dart' as cubit_ui_flow;
import 'package:quanitya_cloud_client/quanitya_cloud_client.dart';
import 'package:serverpod_auth_idp_flutter/serverpod_auth_idp_flutter.dart';
import 'package:flutter_error_privserver/flutter_error_privserver.dart';

import '../app_router.dart';
import '../logic/analytics/analytics_service.dart';
import '../data/repositories/error_box_repository.dart';
import '../features/app_syncing_mode/repositories/app_syncing_repository.dart';
import '../data/dao/fts_search_dao.dart';
import '../data/dao/template_aesthetics_dual_dao.dart';
import '../data/db/app_database.dart';
import '../data/repositories/e2ee_puller.dart';
import '../data/sync/powersync_service.dart';
import '../infrastructure/auth/auth_service.dart';
import '../infrastructure/config/dev_config.dart';
import '../infrastructure/platform/platform_capability_service.dart';
import '../infrastructure/purchase/i_purchase_provider.dart';
import '../infrastructure/purchase/i_purchase_service.dart';
import '../infrastructure/purchase/purchase_models.dart';
import '../infrastructure/error_reporting/error_reporter_service.dart';
import '../infrastructure/feedback/exception_mapper.dart';
import '../infrastructure/fonts/font_preloader_service.dart';
import '../infrastructure/notifications/notification_service.dart';
import '../logic/schedules/services/schedule_generator_service.dart';
import '../features/settings/services/tested_models_service.dart';
import '../features/app_syncing_mode/cubits/app_syncing_cubit.dart';
import '../features/app_syncing_mode/models/app_syncing_mode.dart';
import '../integrations/flutter/health/health_sync_service.dart';
import 'bootstrap.config.dart';

/// Global service locator instance
final GetIt getIt = GetIt.instance;

/// Serverpod client - obtained from DI after bootstrap
Client get client => getIt<Client>();

/// Configures all dependency injection bindings.
/// Generated by build_runner from @injectable and @module annotations.
@InjectableInit()
Future<void> configureDependencies() => getIt.init();

/// Bootstraps the entire application.
///
/// Call this once from main() before runApp().
Future<void> bootstrap() async {
  debugPrint('Bootstrap: Starting...');

  try {
    // 0. Apply dev configuration (including logging settings)
    debugPrint('Bootstrap: Applying dev configuration...');
    DevConfig.applyLoggingConfig();
    debugPrint(
      'Bootstrap: Dev configuration applied (PowerSync logging: ${DevConfig.enablePowerSyncLogging}, connection errors: ${DevConfig.enablePowerSyncConnectionErrors}, other logs: enabled)',
    );

    // 1. Configure all injectable dependencies
    debugPrint('Bootstrap: Configuring dependencies...');
    await configureDependencies();
    debugPrint('Bootstrap: Dependencies configured');

    // 2. Register UI flow service (depends on localization/feedback/loading)
    debugPrint('Bootstrap: Registering UI flow service...');
    _registerUiFlowService();
    debugPrint('Bootstrap: UI flow service registered');

    // 2.5. Configure ErrorPrivserver for privacy-preserving error reporting
    debugPrint('Bootstrap: Configuring ErrorPrivserver...');
    _configureErrorPrivserver();
    debugPrint('Bootstrap: ErrorPrivserver configured');

    // 3. Initialize App Operating Mode (must be early for AuthService)
    debugPrint('Bootstrap: Initializing App Operating Mode...');
    await _initializeAppSyncingMode();
    debugPrint('Bootstrap: App Operating Mode initialized');

    // 4. Initialize E2EE Puller
    if (getIt.isRegistered<IE2EEPuller>()) {
      debugPrint('Bootstrap: Initializing E2EE Puller...');
      final e2eePuller = getIt<IE2EEPuller>();
      await e2eePuller.initialize();
      debugPrint('Bootstrap: E2EE Puller initialized');

      // 4.1. Initialize FTS search index (rebuild only if empty)
      if (getIt.isRegistered<FtsSearchDao>()) {
        final ftsDao = getIt<FtsSearchDao>();
        await ftsDao.ensureTable();
        await ftsDao.rebuildIfEmpty();
        debugPrint('Bootstrap: FTS search index ready');
      }

      // 4.2. One-time migration: encrypt existing plaintext aesthetics
      await _migrateAestheticsToE2EE();
    }

    // 4. Initialize Serverpod client auth
    debugPrint('Bootstrap: Initializing Serverpod client auth...');
    _initializeClientAuth();
    debugPrint('Bootstrap: Serverpod client auth initialized');

    // 5. Initialize AuthService
    if (getIt.isRegistered<AuthService>()) {
      debugPrint('Bootstrap: Initializing AuthService...');
      final authService = getIt<AuthService>();
      await authService.initialize();
      debugPrint('Bootstrap: AuthService initialized');

      // Auto sign-in for registered users (restores JWT session).
      // Free users (never registered) skip this entirely.
      if (await authService.isRegisteredWithServer) {
        try {
          await authService.ensureAuthenticated();
          debugPrint('Bootstrap: JWT session restored');
        } catch (e) {
          debugPrint('Bootstrap: Auto sign-in failed (will retry on purchase): $e');
        }
      }
    }

    // 5.5. Initialize PurchaseService — register providers for supported rails
    if (getIt.isRegistered<IPurchaseService>()) {
      debugPrint('Bootstrap: Initializing PurchaseService...');
      final purchaseService = getIt<IPurchaseService>();
      final platformCaps = getIt<PlatformCapabilityService>();
      final supportedRails = platformCaps.supportedPurchaseRails;
      debugPrint('Bootstrap: Supported purchase rails: $supportedRails');

      if (supportedRails.isNotEmpty &&
          !kIsWeb &&
          getIt.isRegistered<IPurchaseProvider>()) {
        final provider = getIt<IPurchaseProvider>();
        if (supportedRails.contains(provider.rail) &&
            await provider.isAvailable()) {
          await provider.initialize();
          purchaseService.registerProvider(provider);
          await purchaseService.recoverPendingPurchases();
          debugPrint(
            'Bootstrap: Registered ${provider.rail.name} purchase provider',
          );
        } else {
          debugPrint(
            'Bootstrap: Provider ${provider.rail.name} not in supported rails or unavailable',
          );
        }
      } else {
        debugPrint(
          'Bootstrap: No purchase providers to register for this platform',
        );
      }
    }

    // 6. Connect PowerSync for cloud sync (only if not in local mode AND user is authenticated)
    if (getIt.isRegistered<IPowerSyncService>()) {
      final appOperatingCubit = getIt<AppSyncingCubit>();
      final currentMode = appOperatingCubit.state.mode;

      if (currentMode.supportsSync) {
        // Check if user is actually authenticated before trying to connect PowerSync
        final authService = getIt.isRegistered<AuthService>()
            ? getIt<AuthService>()
            : null;
        final isAuthenticated = authService != null
            ? await authService.isAuthenticated()
            : false;

        if (isAuthenticated) {
          debugPrint(
            'Bootstrap: Connecting PowerSync (mode: ${currentMode.name}, authenticated: true)...',
          );
          final powerSync = getIt<IPowerSyncService>();
          final serverpodClient = getIt<Client>();
          await powerSync.connect(serverpodClient, currentMode);
          debugPrint(
            'Bootstrap: PowerSync connected = ${powerSync.isConnected}',
          );
        } else {
          debugPrint(
            'Bootstrap: Skipping PowerSync connection - user not authenticated yet',
          );
        }
      } else {
        debugPrint('Bootstrap: Skipping PowerSync connection (local mode)');
      }
    }

    // 7. Initialize NotificationService
    if (getIt.isRegistered<NotificationService>()) {
      debugPrint('Bootstrap: Initializing NotificationService...');
      final notificationService = getIt<NotificationService>();
      await notificationService.initialize();
      debugPrint('Bootstrap: NotificationService initialized');
    }

    // 8. Preload Google Fonts for offline use
    if (getIt.isRegistered<FontPreloaderService>()) {
      debugPrint('Bootstrap: Preloading Google Fonts...');
      final fontPreloader = getIt<FontPreloaderService>();
      // Don't await - let fonts load in background
      fontPreloader.preloadAllFonts().catchError((e) {
        debugPrint('Bootstrap: Font preloading failed (non-critical): $e');
      });
      debugPrint('Bootstrap: Font preloading started in background');
    }

    // 9. Generate pending todos from schedules
    if (getIt.isRegistered<ScheduleGeneratorService>()) {
      debugPrint('Bootstrap: Generating pending todos...');
      final generator = getIt<ScheduleGeneratorService>();
      final result = await generator.generatePendingTodos();
      debugPrint('Bootstrap: Todo generation complete - $result');
    }

    // 9.5. Sync tested LLM models (fails silently if offline)
    if (getIt.isRegistered<TestedModelsService>()) {
      debugPrint('Bootstrap: Syncing tested LLM models...');
      await getIt<TestedModelsService>().syncOnStartup();
      debugPrint('Bootstrap: Tested LLM models synced');
    }

    // 10. Register health sync resume hook if previously enabled
    if (getIt.isRegistered<HealthSyncService>()) {
      await getIt<HealthSyncService>().registerIfEnabled();
    }

    // 11. Initialize router with correct initial location based on key status
    debugPrint('Bootstrap: Initializing router...');
    await AppRouter.initialize();
    debugPrint('Bootstrap: Router initialized');

    // 11. Track app opened
    if (getIt.isRegistered<AnalyticsService>()) {
      getIt<AnalyticsService>().trackAppOpened();
    }

    // 12. Auto-send analytics if enabled (non-blocking)
    if (getIt.isRegistered<AnalyticsService>() &&
        getIt.isRegistered<AppSyncingRepository>()) {
      _autoSendAnalytics();
    }

    // 13. Auto-send error reports if enabled (non-blocking)
    if (getIt.isRegistered<ErrorReporterService>() &&
        getIt.isRegistered<ErrorBoxRepository>() &&
        getIt.isRegistered<AppSyncingRepository>()) {
      _autoSendErrors();
    }

    debugPrint('Bootstrap: Complete');
  } catch (e, stack) {
    debugPrint('Bootstrap: FAILED - $e');
    debugPrint('Bootstrap: Stack trace:\n$stack');
    rethrow;
  }
}

void _registerUiFlowService() {
  if (!getIt.isRegistered<cubit_ui_flow.IUiFlowService>()) {
    getIt.registerLazySingleton<cubit_ui_flow.IUiFlowService>(
      () => cubit_ui_flow.UiFlowService(
        localization: getIt<cubit_ui_flow.ILocalizationService>(),
        feedback: getIt<cubit_ui_flow.IFeedbackService>(),
        loading: getIt<cubit_ui_flow.ILoadingService>(),
      ),
    );
  }
}

void _initializeClientAuth() {
  // Client is already created by DI, just initialize auth
  final c = getIt<Client>();
  c.authSessionManager = FlutterAuthSessionManager();
  c.auth.initialize();
}

Future<void> _initializeAppSyncingMode() async {
  if (getIt.isRegistered<AppSyncingCubit>()) {
    final appOperatingCubit = getIt<AppSyncingCubit>();
    await appOperatingCubit.initialize();
    debugPrint(
      'Bootstrap: App Operating Mode loaded - current mode: ${appOperatingCubit.state.mode.name}',
    );
  }
}

/// Auto-send analytics events if the user has opted in.
/// Runs in the background — never blocks startup.
void _autoSendAnalytics() {
  Future(() async {
    try {
      final settingsRepo = getIt<AppSyncingRepository>();
      final autoSend = await settingsRepo.getAnalyticsAutoSend();
      if (!autoSend) return;

      debugPrint('Bootstrap: Auto-sending analytics events...');
      final analyticsService = getIt<AnalyticsService>();
      final sent = await analyticsService.sendAllUnsent();
      debugPrint('Bootstrap: Auto-sent $sent analytics events');
    } catch (e) {
      debugPrint('Bootstrap: Analytics auto-send failed (non-critical): $e');
    }
  });
}

/// Auto-send error reports if the user has opted in.
/// Runs in the background — never blocks startup.
void _autoSendErrors() {
  Future(() async {
    try {
      final settingsRepo = getIt<AppSyncingRepository>();
      final autoSend = await settingsRepo.getErrorAutoSend();
      if (!autoSend) return;

      final repo = getIt<ErrorBoxRepository>();
      final reporter = getIt<ErrorReporterService>();
      final errors = await repo.getUnsentErrors();
      if (errors.isEmpty) return;

      debugPrint('Bootstrap: Auto-sending ${errors.length} error reports...');
      final entries = errors.map((e) => e.errorData).toList();
      final sent = await reporter.sendErrorReports(entries);
      debugPrint('Bootstrap: Auto-sent $sent error reports');
    } catch (e) {
      debugPrint('Bootstrap: Error auto-send failed (non-critical): $e');
    }
  });
}

/// Configure ErrorPrivserver for privacy-preserving error reporting.
///
/// Sets up the library to capture PII-free error data from all cubits
/// and store it locally for user-controlled reporting to developers.
void _configureErrorPrivserver() {
  // Configure ErrorPrivserver if dependencies are available
  if (getIt.isRegistered<ErrorReporterService>() &&
      getIt.isRegistered<cubit_ui_flow.IExceptionKeyMapper>() &&
      getIt.isRegistered<ErrorBoxRepository>()) {
    final errorReporter = getIt<ErrorReporterService>();
    final exceptionMapper = getIt<cubit_ui_flow.IExceptionKeyMapper>();
    final errorBoxRepo = getIt<ErrorBoxRepository>();

    ErrorPrivserver.configure(
      ErrorPrivserverConfig(
        storage: errorBoxRepo,
        reporter: (errorEntry) => errorReporter.sendErrorReport(errorEntry),
        errorCodeMapper: ErrorCodeMapper.mapError,
        exceptionMapper: (error) => exceptionMapper.map(error),
      ),
    );

    debugPrint(
      'ErrorPrivserver: Configured with Drift storage and Quanitya exception mapper',
    );
  } else {
    debugPrint(
      'ErrorPrivserver: Skipping configuration - required services not registered',
    );
    debugPrint(
      '  - ErrorReporterService: ${getIt.isRegistered<ErrorReporterService>()}',
    );
    debugPrint(
      '  - IExceptionKeyMapper: ${getIt.isRegistered<cubit_ui_flow.IExceptionKeyMapper>()}',
    );
    debugPrint(
      '  - ErrorBoxRepository: ${getIt.isRegistered<ErrorBoxRepository>()}',
    );
  }
}

/// One-time migration: encrypt existing plaintext aesthetics for E2EE sync.
///
/// Runs on first launch after E2EE aesthetics migration.
/// Reads all local aesthetics, encrypts each via DualDAO,
/// which writes to both local + encrypted tables.
Future<void> _migrateAestheticsToE2EE() async {
  try {
    if (!getIt.isRegistered<TemplateAestheticsDualDao>() ||
        !getIt.isRegistered<AppDatabase>()) {
      return;
    }

    final db = getIt<AppDatabase>();

    // Check if migration already done (encrypted table has data)
    final encryptedCount = await db
        .customSelect('SELECT COUNT(*) as c FROM encrypted_template_aesthetics')
        .getSingle()
        .then((row) => row.read<int>('c'));

    if (encryptedCount > 0) {
      debugPrint('E2EE Migration: Aesthetics already migrated ($encryptedCount records)');
      return;
    }

    // Read all existing plaintext aesthetics
    final existingAesthetics = await db.select(db.templateAesthetics).get();
    if (existingAesthetics.isEmpty) {
      debugPrint('E2EE Migration: No aesthetics to migrate');
      return;
    }

    debugPrint('E2EE Migration: Migrating ${existingAesthetics.length} aesthetics to E2EE');

    final dualDao = getIt<TemplateAestheticsDualDao>();
    await dualDao.bulkUpsert(existingAesthetics);

    debugPrint('E2EE Migration: Complete');
  } catch (e) {
    debugPrint('E2EE Migration: Failed (non-fatal): $e');
  }
}
