import 'package:injectable/injectable.dart';
import 'package:uuid/uuid.dart';

import '../models/analysis_pipeline.dart';
import '../models/analysis_enums.dart';
import '../enums/analysis_output_mode.dart';
import '../enums/calculation.dart';
import '../exceptions/analysis_exceptions.dart';
import '../models/matrix_vector_scalar/operation_registry.dart';

/// Factory for creating analysis pipeline configurations.
@injectable
class PipelineFactory {
  final Uuid _uuid = const Uuid();

  PipelineFactory();

  /// Creates a basic pipeline with a script.
  AnalysisPipelineModel createScriptPipeline({
    required String name,
    required String fieldId,
    required AnalysisOutputMode outputMode,
    required AnalysisSnippetLanguage snippetLanguage,
    required String snippet,
    String? reasoning,
    String? metadataJson,
  }) {
    return AnalysisPipelineModel(
      id: _uuid.v4(),
      name: name,
      fieldId: fieldId,
      outputMode: outputMode,
      snippetLanguage: snippetLanguage,
      snippet: snippet,
      reasoning: reasoning,
      metadataJson: metadataJson,
      updatedAt: DateTime.now(),
    );
  }

  /// Creates an empty pipeline with default script.
  AnalysisPipelineModel createEmptyPipeline({
    required String name,
    required String fieldId,
  }) {
    return AnalysisPipelineModel(
      id: _uuid.v4(),
      name: name,
      fieldId: fieldId,
      outputMode: AnalysisOutputMode.scalar,
      snippetLanguage: AnalysisSnippetLanguage.js,
      snippet: 'return 0;',
      updatedAt: DateTime.now(),
    );
  }

  /// Creates a common extract-values-then-calculate pipeline (Bridge Legacy).
  AnalysisPipelineModel createExtractAndCalculatePipeline({
    required String name,
    required String fieldId,
    required Calculation calculation,
    required String outputKey,
    Map<String, dynamic> params = const {},
  }) {
    final definition = OperationRegistry.instance.getDefinition(calculation);
    if (definition == null) {
      throw AnalysisException('Unknown calculation: ${calculation.name}');
    }

    return AnalysisPipelineModel(
      id: _uuid.v4(),
      name: name,
      fieldId: fieldId,
      outputMode: AnalysisOutputMode.scalar,
      snippetLanguage: AnalysisSnippetLanguage.js,
      snippet: '// Autogenerated legacy bridge\nreturn 0;',
      updatedAt: DateTime.now(),
    );
  }
}
