import 'package:freezed_annotation/freezed_annotation.dart';

part 'category_vector.freezed.dart';
part 'category_vector.g.dart';

/// Array of categorical values: ['light', 'medium', 'heavy']
///
/// Represents categorical data extracted from time series matrices
/// or generated by categorical analysis operations.
@freezed
class CategoryVector with _$CategoryVector {
  const factory CategoryVector(List<String> values) = _CategoryVector;
  
  factory CategoryVector.fromJson(Map<String, dynamic> json) => 
      _$CategoryVectorFromJson(json);
}

/// Extension methods for CategoryVector operations.
///
/// Note: Calculation methods (frequencies, mode, uniqueCategories) have been
/// moved to CalculationRepository for pure math separation.
/// Use CalculationRepository.frequencyDistribution(), categoricalMode(), etc.
extension CategoryVectorExt on CategoryVector {
  /// Number of values in the vector
  int get length => values.length;
  
  /// Check if vector is empty
  bool get isEmpty => values.isEmpty;
  
  /// Check if vector is not empty
  bool get isNotEmpty => values.isNotEmpty;
  
  /// Get first value (throws if empty)
  String get first => values.first;
  
  /// Get last value (throws if empty)
  String get last => values.last;
  
  /// Get value at index (throws if out of bounds)
  String operator [](int index) => values[index];
  
  /// Create new vector with values that satisfy predicate
  CategoryVector where(bool Function(String) test) => 
      CategoryVector(values.where(test).toList());
  
  /// Create new vector with transformed values
  CategoryVector map(String Function(String) transform) => 
      CategoryVector(values.map(transform).toList());
  
  /// Create new vector with values in range [start, end)
  CategoryVector sublist(int start, [int? end]) => 
      CategoryVector(values.sublist(start, end));
}