import 'package:flutter/material.dart';

/// Resolves icon names to IconData without relying on flutter_iconpicker's
/// generated pack maps (which don't populate correctly).
/// 
/// Format: "material:icon_name" where icon_name matches Flutter's Icons.xxx
class IconResolver {
  IconResolver._();
  
  /// Parse icon from "packname:iconname" format and return IconData
  static IconData? resolve(String? iconString) {
    if (iconString == null || !iconString.contains(':')) {
      return null;
    }
    
    final parts = iconString.split(':');
    if (parts.length != 2) return null;
    
    final packName = parts[0].toLowerCase();
    final iconName = parts[1];
    
    // Only support material icons for now
    if (packName != 'material') return null;
    
    return _materialIcons[iconName];
  }
  
  /// Common material icons used in the app
  /// Add more as needed - this is a subset of Flutter's Icons class
  static const Map<String, IconData> _materialIcons = {
    // Health & Fitness
    'fitness_center': Icons.fitness_center,
    'directions_run': Icons.directions_run,
    'directions_walk': Icons.directions_walk,
    'directions_bike': Icons.directions_bike,
    'pool': Icons.pool,
    'sports': Icons.sports,
    'sports_basketball': Icons.sports_basketball,
    'sports_soccer': Icons.sports_soccer,
    'sports_tennis': Icons.sports_tennis,
    'self_improvement': Icons.self_improvement,
    'spa': Icons.spa,
    'favorite': Icons.favorite,
    'favorite_border': Icons.favorite_border,
    'monitor_heart': Icons.monitor_heart,
    'health_and_safety': Icons.health_and_safety,
    'medical_services': Icons.medical_services,
    'medication': Icons.medication,
    'vaccines': Icons.vaccines,
    'healing': Icons.healing,
    
    // Food & Drink
    'restaurant': Icons.restaurant,
    'local_dining': Icons.local_dining,
    'fastfood': Icons.fastfood,
    'local_cafe': Icons.local_cafe,
    'coffee': Icons.coffee,
    'local_bar': Icons.local_bar,
    'wine_bar': Icons.wine_bar,
    'water_drop': Icons.water_drop,
    'local_pizza': Icons.local_pizza,
    'icecream': Icons.icecream,
    'cake': Icons.cake,
    'egg': Icons.egg,
    'apple': Icons.apple,
    'lunch_dining': Icons.lunch_dining,
    'dinner_dining': Icons.dinner_dining,
    'breakfast_dining': Icons.breakfast_dining,
    'brunch_dining': Icons.brunch_dining,
    'kitchen': Icons.kitchen,
    
    // Sleep & Rest
    'bedtime': Icons.bedtime,
    'nightlight': Icons.nightlight,
    'nights_stay': Icons.nights_stay,
    'hotel': Icons.hotel,
    'king_bed': Icons.king_bed,
    'single_bed': Icons.single_bed,
    
    // Mood & Mental
    'mood': Icons.mood,
    'mood_bad': Icons.mood_bad,
    'sentiment_satisfied': Icons.sentiment_satisfied,
    'sentiment_dissatisfied': Icons.sentiment_dissatisfied,
    'sentiment_neutral': Icons.sentiment_neutral,
    'sentiment_very_satisfied': Icons.sentiment_very_satisfied,
    'sentiment_very_dissatisfied': Icons.sentiment_very_dissatisfied,
    'psychology': Icons.psychology,
    'emoji_emotions': Icons.emoji_emotions,
    'emoji_events': Icons.emoji_events,
    'emoji_nature': Icons.emoji_nature,
    'emoji_objects': Icons.emoji_objects,
    'emoji_people': Icons.emoji_people,
    
    // Work & Productivity
    'work': Icons.work,
    'work_outline': Icons.work_outline,
    'business_center': Icons.business_center,
    'laptop': Icons.laptop,
    'computer': Icons.computer,
    'desktop_windows': Icons.desktop_windows,
    'phone_android': Icons.phone_android,
    'phone_iphone': Icons.phone_iphone,
    'task': Icons.task,
    'task_alt': Icons.task_alt,
    'checklist': Icons.checklist,
    'assignment': Icons.assignment,
    'assignment_turned_in': Icons.assignment_turned_in,
    'pending_actions': Icons.pending_actions,
    'schedule': Icons.schedule,
    'event': Icons.event,
    'event_available': Icons.event_available,
    'calendar_today': Icons.calendar_today,
    'calendar_month': Icons.calendar_month,
    'today': Icons.today,
    'alarm': Icons.alarm,
    'timer': Icons.timer,
    'hourglass_empty': Icons.hourglass_empty,
    'hourglass_full': Icons.hourglass_full,
    
    // Money & Finance
    'attach_money': Icons.attach_money,
    'money': Icons.money,
    'payments': Icons.payments,
    'account_balance': Icons.account_balance,
    'account_balance_wallet': Icons.account_balance_wallet,
    'credit_card': Icons.credit_card,
    'savings': Icons.savings,
    'paid': Icons.paid,
    'receipt': Icons.receipt,
    'receipt_long': Icons.receipt_long,
    'shopping_cart': Icons.shopping_cart,
    'shopping_bag': Icons.shopping_bag,
    'store': Icons.store,
    
    // Education & Learning
    'school': Icons.school,
    'menu_book': Icons.menu_book,
    'auto_stories': Icons.auto_stories,
    'library_books': Icons.library_books,
    'book': Icons.book,
    'bookmark': Icons.bookmark,
    'bookmark_border': Icons.bookmark_border,
    'class_': Icons.class_,
    'science': Icons.science,
    'calculate': Icons.calculate,
    'functions': Icons.functions,
    'translate': Icons.translate,
    'language': Icons.language,
    
    // Social & Communication
    'people': Icons.people,
    'person': Icons.person,
    'person_outline': Icons.person_outline,
    'group': Icons.group,
    'groups': Icons.groups,
    'family_restroom': Icons.family_restroom,
    'chat': Icons.chat,
    'chat_bubble': Icons.chat_bubble,
    'message': Icons.message,
    'forum': Icons.forum,
    'call': Icons.call,
    'video_call': Icons.video_call,
    'email': Icons.email,
    'mail': Icons.mail,
    'share': Icons.share,
    'thumb_up': Icons.thumb_up,
    'thumb_down': Icons.thumb_down,
    
    // Travel & Places
    'flight': Icons.flight,
    'directions_car': Icons.directions_car,
    'directions_bus': Icons.directions_bus,
    'train': Icons.train,
    'subway': Icons.subway,
    'local_taxi': Icons.local_taxi,
    'two_wheeler': Icons.two_wheeler,
    'sailing': Icons.sailing,
    'beach_access': Icons.beach_access,
    'terrain': Icons.terrain,
    'landscape': Icons.landscape,
    'park': Icons.park,
    'forest': Icons.forest,
    'nature': Icons.nature,
    'nature_people': Icons.nature_people,
    'home': Icons.home,
    'house': Icons.house,
    'apartment': Icons.apartment,
    'location_on': Icons.location_on,
    'place': Icons.place,
    'map': Icons.map,
    'explore': Icons.explore,
    
    // Entertainment & Hobbies
    'movie': Icons.movie,
    'theaters': Icons.theaters,
    'tv': Icons.tv,
    'live_tv': Icons.live_tv,
    'music_note': Icons.music_note,
    'headphones': Icons.headphones,
    'mic': Icons.mic,
    'radio': Icons.radio,
    'videogame_asset': Icons.videogame_asset,
    'sports_esports': Icons.sports_esports,
    'casino': Icons.casino,
    'palette': Icons.palette,
    'brush': Icons.brush,
    'draw': Icons.draw,
    'edit': Icons.edit,
    'create': Icons.create,
    'camera': Icons.camera,
    'camera_alt': Icons.camera_alt,
    'photo_camera': Icons.photo_camera,
    'photo': Icons.photo,
    'image': Icons.image,
    'collections': Icons.collections,
    
    // Weather & Nature
    'wb_sunny': Icons.wb_sunny,
    'cloud': Icons.cloud,
    'cloud_queue': Icons.cloud_queue,
    'thunderstorm': Icons.thunderstorm,
    'ac_unit': Icons.ac_unit,
    'waves': Icons.waves,
    'air': Icons.air,
    'eco': Icons.eco,
    'grass': Icons.grass,
    'yard': Icons.yard,
    'pets': Icons.pets,
    
    // Common UI Icons
    'star': Icons.star,
    'star_border': Icons.star_border,
    'star_half': Icons.star_half,
    'grade': Icons.grade,
    'check': Icons.check,
    'check_circle': Icons.check_circle,
    'check_box': Icons.check_box,
    'done': Icons.done,
    'done_all': Icons.done_all,
    'close': Icons.close,
    'cancel': Icons.cancel,
    'add': Icons.add,
    'add_circle': Icons.add_circle,
    'remove': Icons.remove,
    'remove_circle': Icons.remove_circle,
    'delete': Icons.delete,
    'delete_outline': Icons.delete_outline,
    'edit_outlined': Icons.edit_outlined,
    'settings': Icons.settings,
    'tune': Icons.tune,
    'build': Icons.build,
    'construction': Icons.construction,
    'info': Icons.info,
    'info_outline': Icons.info_outline,
    'help': Icons.help,
    'help_outline': Icons.help_outline,
    'warning': Icons.warning,
    'error': Icons.error,
    'error_outline': Icons.error_outline,
    'notification_important': Icons.notification_important,
    'notifications': Icons.notifications,
    'notifications_active': Icons.notifications_active,
    'bolt': Icons.bolt,
    'flash_on': Icons.flash_on,
    'lightbulb': Icons.lightbulb,
    'tips_and_updates': Icons.tips_and_updates,
    'flag': Icons.flag,
    'outlined_flag': Icons.outlined_flag,
    'push_pin': Icons.push_pin,
    'label': Icons.label,
    'local_offer': Icons.local_offer,
    'loyalty': Icons.loyalty,
    'verified': Icons.verified,
    'new_releases': Icons.new_releases,
    'trending_up': Icons.trending_up,
    'trending_down': Icons.trending_down,
    'trending_flat': Icons.trending_flat,
    'insights': Icons.insights,
    'analytics': Icons.analytics,
    'bar_chart': Icons.bar_chart,
    'pie_chart': Icons.pie_chart,
    'show_chart': Icons.show_chart,
    'timeline': Icons.timeline,
    'leaderboard': Icons.leaderboard,
    'speed': Icons.speed,
    'straighten': Icons.straighten,
    'scale': Icons.scale,
    'monitor_weight': Icons.monitor_weight,
    'height': Icons.height,
    'square_foot': Icons.square_foot,
    'thermostat': Icons.thermostat,
    'device_thermostat': Icons.device_thermostat,
    'opacity': Icons.opacity,
    'percent': Icons.percent,
    'numbers': Icons.numbers,
    'tag': Icons.tag,
    'description': Icons.description,
    'article': Icons.article,
    'note': Icons.note,
    'note_add': Icons.note_add,
    'sticky_note_2': Icons.sticky_note_2,
    'text_snippet': Icons.text_snippet,
    'list': Icons.list,
    'list_alt': Icons.list_alt,
    'format_list_bulleted': Icons.format_list_bulleted,
    'format_list_numbered': Icons.format_list_numbered,
    'view_list': Icons.view_list,
    'view_module': Icons.view_module,
    'grid_view': Icons.grid_view,
    'dashboard': Icons.dashboard,
    'widgets': Icons.widgets,
    'category': Icons.category,
    'folder': Icons.folder,
    'folder_open': Icons.folder_open,
    'inventory': Icons.inventory,
    'inventory_2': Icons.inventory_2,
    'archive': Icons.archive,
    'unarchive': Icons.unarchive,
    'save': Icons.save,
    'save_alt': Icons.save_alt,
    'download': Icons.download,
    'upload': Icons.upload,
    'cloud_upload': Icons.cloud_upload,
    'cloud_download': Icons.cloud_download,
    'sync': Icons.sync,
    'refresh': Icons.refresh,
    'autorenew': Icons.autorenew,
    'loop': Icons.loop,
    'repeat': Icons.repeat,
    'replay': Icons.replay,
    'undo': Icons.undo,
    'redo': Icons.redo,
    'history': Icons.history,
    'update': Icons.update,
    'access_time': Icons.access_time,
    'watch_later': Icons.watch_later,
    'more_time': Icons.more_time,
    'timelapse': Icons.timelapse,
    'snooze': Icons.snooze,
    'power_settings_new': Icons.power_settings_new,
    'restart_alt': Icons.restart_alt,
    'play_arrow': Icons.play_arrow,
    'pause': Icons.pause,
    'stop': Icons.stop,
    'skip_next': Icons.skip_next,
    'skip_previous': Icons.skip_previous,
    'fast_forward': Icons.fast_forward,
    'fast_rewind': Icons.fast_rewind,
    'shuffle': Icons.shuffle,
    'volume_up': Icons.volume_up,
    'volume_down': Icons.volume_down,
    'volume_mute': Icons.volume_mute,
    'volume_off': Icons.volume_off,
    'brightness_high': Icons.brightness_high,
    'brightness_low': Icons.brightness_low,
    'brightness_medium': Icons.brightness_medium,
    'dark_mode': Icons.dark_mode,
    'light_mode': Icons.light_mode,
    'contrast': Icons.contrast,
    'visibility': Icons.visibility,
    'visibility_off': Icons.visibility_off,
    'lock': Icons.lock,
    'lock_open': Icons.lock_open,
    'key': Icons.key,
    'vpn_key': Icons.vpn_key,
    'security': Icons.security,
    'shield': Icons.shield,
    'verified_user': Icons.verified_user,
    'privacy_tip': Icons.privacy_tip,
    'fingerprint': Icons.fingerprint,
    'face': Icons.face,
    'face_2': Icons.face_2,
    'face_3': Icons.face_3,
    'face_4': Icons.face_4,
    'face_5': Icons.face_5,
    'face_6': Icons.face_6,
    'elderly': Icons.elderly,
    'child_care': Icons.child_care,
    'child_friendly': Icons.child_friendly,
    'pregnant_woman': Icons.pregnant_woman,
    'accessibility': Icons.accessibility,
    'accessible': Icons.accessible,
    'wc': Icons.wc,
    'bathtub': Icons.bathtub,
    'shower': Icons.shower,
    'hot_tub': Icons.hot_tub,
    'dry': Icons.dry,
    'soap': Icons.soap,
    'sanitizer': Icons.sanitizer,
    'clean_hands': Icons.clean_hands,
    'wash': Icons.wash,
    'local_laundry_service': Icons.local_laundry_service,
    'iron': Icons.iron,
    'checkroom': Icons.checkroom,
    'dry_cleaning': Icons.dry_cleaning,
  };
}
