import 'package:freezed_annotation/freezed_annotation.dart';
import 'type_definitions.dart';
import 'stat_scalar.dart';

part 'value_vector.freezed.dart';
part 'value_vector.g.dart';

/// Array of numeric values: [7.5, 8.2, 6.9]
///
/// Represents a 1D array of values extracted from time series data
/// or generated by analysis operations.
@freezed
abstract class ValueVector with _$ValueVector {
  const ValueVector._();
  const factory ValueVector(Vector values) = _ValueVector;
  
  factory ValueVector.fromJson(Map<String, dynamic> json) => 
      _$ValueVectorFromJson(json);
}

/// Extension methods for ValueVector mathematical operations.
extension ValueVectorExt on ValueVector {
  /// Number of values in the vector
  int get length => values.length;
  
  /// Check if vector is empty
  bool get isEmpty => values.isEmpty;
  
  /// Check if vector is not empty
  bool get isNotEmpty => values.isNotEmpty;
  
  /// Get first value (throws if empty)
  Numeric get first => values.first;
  
  /// Get last value (throws if empty)
  Numeric get last => values.last;
  
  /// Sum of all values
  StatScalar get sum => StatScalar(
    values.fold<Numeric>(0, (a, b) => a + b)
  );
  
  /// Arithmetic mean of values
  StatScalar get mean => isEmpty 
      ? const StatScalar(0) 
      : StatScalar(sum.value / length);
  
  /// Minimum value
  StatScalar get min => isEmpty 
      ? const StatScalar(0)
      : StatScalar(values.reduce((a, b) => a < b ? a : b));
  
  /// Maximum value
  StatScalar get max => isEmpty 
      ? const StatScalar(0)
      : StatScalar(values.reduce((a, b) => a > b ? a : b));
  
  /// Range (max - min)
  StatScalar get range => StatScalar(max.value - min.value);
  
  /// Get value at index (throws if out of bounds)
  Numeric operator [](int index) => values[index];
  
  /// Create new vector with values that satisfy predicate
  ValueVector where(bool Function(Numeric) test) => 
      ValueVector(values.where(test).toList());
  
  /// Create new vector with transformed values
  ValueVector map(Numeric Function(Numeric) transform) => 
      ValueVector(values.map(transform).toList());
  
  /// Create new vector with values in range [start, end)
  ValueVector sublist(int start, [int? end]) => 
      ValueVector(values.sublist(start, end));
}