// Mocks generated by Mockito 5.4.6 from annotations
// in quanitya_flutter/test/features/settings/cubits/recovery_key_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:anonaccount_client/anonaccount_client.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:quanitya_flutter/infrastructure/auth/account_service.dart'
    as _i3;
import 'package:quanitya_flutter/infrastructure/auth/auth_service.dart' as _i2;
import 'package:serverpod_client/serverpod_client.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAccountCreationResult_0 extends _i1.SmartFake
    implements _i2.AccountCreationResult {
  _FakeAccountCreationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AccountService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountService extends _i1.Mock implements _i3.AccountService {
  MockAccountService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AccountCreationResult> createAccount({
    required String? deviceLabel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAccount, [], {#deviceLabel: deviceLabel}),
            returnValue: _i4.Future<_i2.AccountCreationResult>.value(
              _FakeAccountCreationResult_0(
                this,
                Invocation.method(#createAccount, [], {
                  #deviceLabel: deviceLabel,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AccountCreationResult>);

  @override
  _i4.Future<void> registerAccountWithServer({required String? deviceLabel}) =>
      (super.noSuchMethod(
            Invocation.method(#registerAccountWithServer, [], {
              #deviceLabel: deviceLabel,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> ensureRegistered({
    required String? deviceLabel,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#ensureRegistered, [], {
              #deviceLabel: deviceLabel,
              #force: force,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> recoverAccount({
    required String? ultimatePrivateKey,
    required String? deviceLabel,
    bool? eraseExisting = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recoverAccount, [], {
              #ultimatePrivateKey: ultimatePrivateKey,
              #deviceLabel: deviceLabel,
              #eraseExisting: eraseExisting,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> validateRecoveryKey(String? jwk) =>
      (super.noSuchMethod(
            Invocation.method(#validateRecoveryKey, [jwk]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> recoverFromCrossDeviceKey({required String? deviceLabel}) =>
      (super.noSuchMethod(
            Invocation.method(#recoverFromCrossDeviceKey, [], {
              #deviceLabel: deviceLabel,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> recreateCrossDeviceKey() =>
      (super.noSuchMethod(
            Invocation.method(#recreateCrossDeviceKey, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> importUltimateKeyForSession(String? jwk) =>
      (super.noSuchMethod(
            Invocation.method(#importUltimateKeyForSession, [jwk]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void clearUltimateKeySession() => super.noSuchMethod(
    Invocation.method(#clearUltimateKeySession, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<List<_i5.AccountDevice>> listDevices() =>
      (super.noSuchMethod(
            Invocation.method(#listDevices, []),
            returnValue: _i4.Future<List<_i5.AccountDevice>>.value(
              <_i5.AccountDevice>[],
            ),
          )
          as _i4.Future<List<_i5.AccountDevice>>);

  @override
  _i4.Future<void> revokeDevice(
    _i6.UuidValue? deviceId, {
    required String? ultimateKeyJwk,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #revokeDevice,
              [deviceId],
              {#ultimateKeyJwk: ultimateKeyJwk},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getCurrentDevicePublicKeyHex() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentDevicePublicKeyHex, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}
